# Spring config
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: create
    show-sql: true
    properties.hibernate:
      format_sql: true
      jdbc.lob.non_contextual_creation: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa #change
    initialization-mode: always
  h2:
    console:
      enabled: true
